# Generated by Django 4.2.5 on 2023-12-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_progucto_created_progucto_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progucto',
            new_name='Producto',
        ),
    ]
